### PR TITLE
Change from serial port to GPIO pins

### PR DESCRIPTION
**Pull request by Suyooo**
Since door status has been broken for a while after the serial on the RPi failed, gurkih and I tinkered a little with it today. Someone had already cut the serial wire and added a new header, so the layout might seem a little odd.
I also changed the check from the user name to the user ID so the update script can be started with cronjob (I don't know how it was done before?)
This script is running on the RPi in the lab already and seems to be working fine.

### CODE REVIEW

**Comment by lgrunenberg** [comment]
The code configures the Raspberry PI GPIO pins 2 and 27, did you change the pin header accordingly? The pin header was made to connect the door reed switch to GPIO pin 18 and +5V with a pull down resistor to ground.

If so: IIRC the door status update was assigned to David and me so please stop ripping things apart before asking around what the original thought was.

EDIT: i understood what's the purpose of setting the GPIO pins as you do. By setting the GPIO pin 27 as an output no change to the pin header is necessary. While that might work the pin header must be connected oddly. But i think that's acceptable.

**Comment by Suyooo** [comment]
I was asked by gurkih to look at the script this afternoon when I came in. Nothing has been "ripped apart", I have just connected the header and changed the script. I was originally planning to use the 3.3V pin, when I noticed the cable had already been changed I just looked for a matching GND pin instead of a 5V pin. If you feel like 18/5V works better we can still change the pins as the header is still the same as before (we'd only have to change the path where the value is read => might be a good addition to add the GPIO pin number as a configuration variable?), but it seems this current setup works fine.

**Comment by lgrunenberg** [comment]
Configuration variables are always a good idea :)

I actually quite like your approach as the GPIO pin is not overdriven by 5 V. I do not remember why we decided to use the 5 V supply in the first place. Maybe at some time a proper 40 pin connector housing should be used to avoid confusion.

Thank you for fixing the door status and sorry for my harsh tone :)

**Comment by mgmax** [comment]
Can the onboot code be simply included in the script? If not, please add documentation on how to install the onboot code.

The update script was originally supposed to be set up as systemd timer (see the timer and service files).

**Comment by mgmax** [comment]
Please also update the README.md in the main folder ("ws01", "serial port")

**Comment by Suyooo** [comment]
These commits have only been tested on my computer as I'm not in the lab until tomorrow. I'll test them on the RPi in the lab tomorrow if no one is available before.

**Comment by Suyooo** [comment]
This version of the script is now running on the RPi in the lab and seems to be working fine.
I also changed the pin setup to something more sensible (3V3 and GPIO17), but right now the old header is connected to the pins via jumper cables. As Lukas has said it's probably good idea to make a new pin header but I couldn't make that yet as I couldn't find the headers for crimping (do we have any? If I can find them I can finish it tomorrow). However, the configuration should not require any more changes.

**Comment by gurkih** [comment]
the script is using a simple cronjob because i consider the systemd timer approach a bit "overkill" (and, more importantly, it was buggy and didnt work ...)

**Comment by mgmax** [comment]
Do it as you like as long as it is documented :-)

**Comment by sedrubal** [comment]
I don't see why systems timer are overkill. On modern linux distributions cronjobs are migrated to timers and sometimes crond isn't even installed any more. Compared to cronjobs, systemd timers have many advantages like sane logging by default, debugging opportunities, information about, when the job runs next and many more. I recommend keeping the timer. As it worked well on ws01 for years, I can't imagine that it is that broken. In the end it's up to the person that maintains the script.

**Pull request merged**
